import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Roboto } from 'next/font/google';
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryCkientProvider";




const roboto = Roboto({
  subsets:['latin'],
  weight: ['100', '300', '400', '500', '700' , '900'],
  variable: "--font-roboto"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ roboto.variable }>
        <QueryClientProvider>
        <AuthProvider>
          <Theme>
          <Navbar/>
          {children}
          </Theme>
        </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
