import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import Navbar from "../components/Navbar";
import AuthProvider from "../components/providers/Provider";
import QueryClientProvider from "../components/providers/QueryClientProvider";
import "@radix-ui/themes/styles.css";
import "./globals.css"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <AuthProvider>
            <Theme>
              <Navbar />
              {children}
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
